version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - '3022:3022'
    volumes:
      - ./data:/var/lib/postgres

    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: my_user
      POSTGRES_DB: app

