version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    ports:
      - '3022:3022'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'POSTGRESQL_USERNAME=my_user'
      - 'POSTGRESQL_PASSWORD=password123'
      - 'POSTGRESQL_DATABASE=app'

volumes:
  postgresql_data:
    driver: local